name: Python Testing, Linting, and Build

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]  

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --output-format=github .

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with Pytest
      run: |
        pip install pytest pytest-cov
        pytest test_kingdom.py test_customer.py test_transaction.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/

  build:
    runs-on: ubuntu-latest

    needs: test  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile your_script.py
